// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String ping({required String input}) =>
    RustLib.instance.api.crateApiSimplePing(input: input);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalAi>>
abstract class LocalAi implements RustOpaqueInterface {
  String generate({required String prompt, required BigInt maxTokens});

  factory LocalAi({
    required List<int> weightsBytes,
    required List<int> tokenizerBytes,
  }) => RustLib.instance.api.crateApiSimpleLocalAiNew(
    weightsBytes: weightsBytes,
    tokenizerBytes: tokenizerBytes,
  );
}
