// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRCPrcH2PFWqng1R9wB6ATxfloYNmoos',
    appId: '1:780384125037:web:832032212535ae5fd6bf64',
    messagingSenderId: '780384125037',
    projectId: 'tianhaozhou',
    authDomain: 'tianhaozhou.firebaseapp.com',
    storageBucket: 'tianhaozhou.firebasestorage.app',
    measurementId: 'G-6LY30NCRXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqotgoML54CmiYbmybmk7cOj1rxut62U',
    appId: '1:780384125037:android:57ce5a546a739ab9d6bf64',
    messagingSenderId: '780384125037',
    projectId: 'tianhaozhou',
    storageBucket: 'tianhaozhou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbkUj2hvArRoWTlSn2JwTqlutLpasBQ0U',
    appId: '1:780384125037:ios:fc9eac4f2b456bbdd6bf64',
    messagingSenderId: '780384125037',
    projectId: 'tianhaozhou',
    storageBucket: 'tianhaozhou.firebasestorage.app',
    iosBundleId: 'com.hejitech.tianhaozhouHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbkUj2hvArRoWTlSn2JwTqlutLpasBQ0U',
    appId: '1:780384125037:ios:fc9eac4f2b456bbdd6bf64',
    messagingSenderId: '780384125037',
    projectId: 'tianhaozhou',
    storageBucket: 'tianhaozhou.firebasestorage.app',
    iosBundleId: 'com.hejitech.tianhaozhouHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnRCPrcH2PFWqng1R9wB6ATxfloYNmoos',
    appId: '1:780384125037:web:4b8ae297ce688c26d6bf64',
    messagingSenderId: '780384125037',
    projectId: 'tianhaozhou',
    authDomain: 'tianhaozhou.firebaseapp.com',
    storageBucket: 'tianhaozhou.firebasestorage.app',
    measurementId: 'G-QCPFQ1ZJ75',
  );
}
